- name: Run backend application container
  docker_container:
    name: backend_app
    image: "gbrom/tp-devops-simple-api:latest"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: db_network      # connects to database
      - name: app_network     # connects to proxy
    env:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://my_db:5432/postgres"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "password"
