version: '3.9'  # latest stable Compose file version

services:
  backend:
    build:
      context: ./simpleapi   # folder containing Dockerfile for your API
      dockerfile: Dockerfile.simpleapi
    container_name: simple-api
    networks:
      - app-network
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
    restart: unless-stopped
    # API port not exposed to host, only internal network

  database:
    build:
      context: .. # folder containing Dockerfile.postgres
      dockerfile: Dockerfile
    container_name: my-postgres
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  httpd:
    build:
      context: ./http-server    # folder containing Dockerfile for Apache
      dockerfile: Dockerfile
    container_name: apache-server
    networks:
      - app-network
    ports:
      - "8084:80"         # exposed to host
    depends_on:
      - backend
    restart: unless-stopped

# Shared network for communication between containers
networks:
  app-network:
    driver: bridge

# Persistent volume for Postgres data
volumes:
  postgres-data: