- name: Run HTTPD / proxy container
  docker_container:
    name: httpd_proxy
    image: "gbrom/tp-devops-http-server:latest"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: my_network
    ports:
      - "80:80"
    env:
      PAGE_NAME: "app"
