name: CD Pipeline

on:
  push:
    tags:
      - 'v*.*.*'   # only trigger for version tags, e.g., v1.0.0

jobs:
  staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Playbook on Staging
        run: |
          ansible-playbook -i inventories/staging.yml playbook.yml --become
        env:
          ANSIBLE_PRIVATE_KEY: ${{ secrets.STAGING_SSH_KEY }}

      - name: Run smoke tests
        run: |
          curl -f http://staging.example.com/health || exit 1

  production:
    name: Deploy to Production
    needs: staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Playbook on Production
        run: |
          ansible-playbook -i inventories/setup.yml playbook.yml --become
        env:
          ANSIBLE_PRIVATE_KEY: ${{ secrets.PROD_SSH_KEY }}
